const EVENT_TYPE = {
    PAGE_VIEW: 'page_view',
    VIEW_ANY_REPORT: 'view_any_report',
    VIEW_REPORT_KEYWORD: 'view_report_keyword',
    VIEW_REPORT_CATEGORY: 'view_report_category',
    VIEW_REPORT_BRAND: 'view_report_brand',
    VIEW_REPORT_COMMUNITY: 'view_report_community',
    VIEW_SEARCH_RESULTS: 'view_search_results',
    CLICK_RELATED_REPORT: 'click_related_report',
    // CLICK_FAST_ANALYZE: 'click_fast_analyze',
    // FAST_ANALYZE: 'fast_analyze',
    SHOW_POPUP_BUY_REPORT: 'show_popup_buy_report',
    VIEW_CHECKOUT_REPORT: 'view_checkout_report',
    CLICK_CHECKOUT_REPORT: 'click_checkout_report',
    DOWNLOAD_REPORT: 'download_report',
    PAYMENT_SUCCESS_REPORT: 'payment_success_report',
    CLICK_PRICING_PLAN: 'click_pricing_plan',
    VIEW_CHECKOUT_PACKAGE: 'view_checkout_package',
    CLICK_CHECKOUT_PACKAGE: 'click_checkout_package',
    PAYMENT_SUCCESS_PACKAGE: 'payment_success_package',
    SUBMIT_FORM_CONTACT: 'submit_form_contact',
    SUBMIT_FORM_COMMUNITY_REPORT: 'submit_form_community_report',
    SUBMIT_FORM_HOMEPAGE: 'submit_form_homepage',
    COPY_REFERRAL_CODE: 'copy_referral_code',
    VIEW_REPORT_REPORTS: 'view_report_reports',
    VIEW_PRICING: 'view_pricing',
    CLICK_HOMEPAGE_SEARCH_BAR: 'click_homepage_search_bar',
    CLICK_SUGGESTION_KEYWORD: 'click_suggestion_keyword',
    SHOW_POPUP_CONVERT_TO_ANALYTICS: 'show_popup_convert_to_analytics',
    CLICK_RELATED_REPORT_SEARCH_RESULT: 'click_related_report_search_result',
    VIEW_SMART_ANALYTIC: 'view_smart_analytic',
    VIDEO_START: 'video_start',
};

export {
    EVENT_TYPE
};