name: Call a templated workflow 

permissions: read-all

on:
  push:
    branches: [ "production","product-ereport-vn" ]
env:  
  PUBLIC_REGISTRY: ${{ vars.PUBLIC_REGISTRY }}

jobs:
  include-builds:  
    # uses: beecost/workflow-template/.github/workflows/template-workflows-build-fe.yml@master  
    uses: beecost/cicd-template/.github/workflows/build-stage-ereport-fe-prod.yml@main  
    secrets: inherit  
  
  include-deploy:
    uses: beecost/workflow-template/.github/workflows/template-workflows-deploy-fe.yml@master
    secrets: inherit  
    needs: [include-builds]
