name: Call a templated workflow 

permissions: read-all

on:
  push:
    branches: [ "staging","production","product-ereport-vn" ]

jobs:
  include-builds:
    uses: beecost/cicd-template/.github/workflows/build-stage-ereport-fe.yml@main  
    secrets: inherit  
    # uses: beecost/workflow-template/.github/workflows/template-workflows-build-fe.yml@master
    # secrets: inherit
  
  include-deploy:
    uses: beecost/workflow-template/.github/workflows/template-workflows-deploy-fe.yml@master
    secrets: inherit  
    needs: [include-builds]
