name: Caller workflow 01

permissions: read-all

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]
jobs:

  precheck2:

    uses: beecost/workflow-template/.github/workflows/template-workflows-steps.yml@master
    secrets: inherit