name: Call a templated workflow 

permissions: read-all

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "staging","production","build-pdf" ]
env:  
  PUBLIC_REGISTRY: ${{ vars.PUBLIC_REGISTRY }}

jobs:
  # include-builds:
  #   uses: beecost/workflow-template/.github/workflows/template-workflows-build-be.yml@master
  #   secrets: inherit
  include-builds:  
    uses: beecost/cicd-template/.github/workflows/build-stage-selfhosted.yml@main  
    secrets: inherit  
  
  include-deploy:

    uses: beecost/workflow-template/.github/workflows/template-workflows-deploy-fe.yml@master
    secrets: inherit  
    needs: [include-builds]
